import React, { useState } from "react";
import Head from "next/head";
import Nav from "@/components/Nav";
import DayForecast2 from "@/components/DayForecast2";
import { FaSearch } from "react-icons/fa";
import CityResult from "@/components/CityResult";
import getCities from "./api/getCities";

const Cities = () => {
  const [searchResults, setSearchResults] = useState([]);
  const [loading, setLoading] = useState(false);

  const handleKeyPress = async (e) => {
    if (e.key === "Enter") {
      e.preventDefault();
      setLoading(true);
      try {
        const data = await getCities(e);

        setSearchResults(data);
        setLoading(false);
      } catch (error) {
        console.log(error.message);
      }
    }
  };

  return (
    <>
      <Head>
        <title>Cities | Greezy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#262626]">
        <div className="flex flex-col w-full min-h-[100dvh] xl:h-screen gap-12 p-4 xl:flex-row xl:gap-8">
          <Nav />
          <section className="flex flex-col p-4 pb-5 space-y-10 grow background rounded-3xl md:p-8 h-fit xl:h-auto">
            <div className="flex items-center w-full gap-4">
              <h1 className="text-4xl text-center text-white xl:text-7xl">
                Cities
              </h1>

              <form className="flex items-center w-full h-10 gap-2 pl-2 border rounded-lg">
                <FaSearch color="#fff" />
                <input
                  type="search"
                  className="w-full h-full text-white bg-transparent outline-none"
                  placeholder="Search for a city"
                  onKeyDown={handleKeyPress}
                ></input>
              </form>
            </div>

            {(loading == false) & (searchResults.length == 0) ? (
              <div className="flex items-center justify-center p-8 pt-4 grow">
                <h1 className="text-2xl text-white">No searches...</h1>
              </div>
            ) : (loading == false) & (searchResults.length > 0) ? (
              <div className="grid grid-cols-1 gap-10 xl:gap-y-14 md:grid-cols-3 grow md:grow-0">
                {searchResults.map((result) => (
                  <CityResult key={Math.random() * 10000} result={result} />
                ))}
              </div>
            ) : (
              <div className="flex items-center justify-center p-8 pt-4 grow">
                <h1 className="text-3xl text-white">Locating...</h1>
              </div>
            )}
          </section>

          <DayForecast2 />
        </div>
      </main>
    </>
  );
};

export default Cities;
