import Head from "next/head";

import LocationNeeded from "@/components/Feedback/LocationNeeded";
import MapInfo from "@/components/Map";
import Nav from "@/components/Nav";
import React, { useEffect, useState } from "react";
import { FaLocationArrow } from "react-icons/fa";
import { useLocalStorage } from "react-use";

const Map = () => {
  const [askUser, setAskUser] = useState(null);
  const [confirmed, setConfirmed] = useLocalStorage("confirmed");
  const [recalculate, setRecalculate] = useState(false);

  useEffect(() => {
    if (confirmed !== "true") {
      setAskUser(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handlePinpoint = () => {
    if (confirmed === "true") {
      setRecalculate((prev) => !prev);
      return;
    }

    setAskUser(true);
  };

  const handleLocationClick = () => {
    setConfirmed("true");
    setAskUser(false);
  };

  const handleActive = () => {
    setAskUser(false);
  };

  return (
    <>
      <Head>
        <title>Map | Greezy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center w-screen h-[100dvh] gap-8 bg-[#262626] xl:p-4 pb-[58px] xl:pb-4">
        <Nav />
        <section className="relative h-full overflow-hidden xl:border xl:rounded-3xl grow">
          <MapInfo confirmed={confirmed} recalculate={recalculate} />
          <button
            className="absolute z-10 px-10 py-3 text-white duration-300 bg-black rounded-lg rounded-tl-none rounded-br-none right-3 top-3 xl:top-0 xl:right-0 xl:py-4 xl:px-10 xl:rounded-tr-3xl"
            onClick={handlePinpoint}
          >
            <FaLocationArrow />
          </button>
        </section>
      </main>

      {askUser && (
        <LocationNeeded
          handleActive={handleActive}
          handleLocationClick={handleLocationClick}
        />
      )}
    </>
  );
};

export default Map;
